mongodb-js/data-service

package.json
cc @durran
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/1)
=> Unpin Kerberos so we don't have multiple versions in Compass

lib/data-service.js, lib/router.js, test/data-service.test.js, test/router.test.js
Also adding `options` argument to data-service#indexes to conform with route handling (see `DataService#_generateArguments`).
@durran can you review if this change makes sense?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/5)
=> add /collections/:ns/indexes route

lib/native-client.js, package.json, test/data-service.test.js
@durran can you please review?
The new index model fetches information from multiple places
- `db.collection.getIndexes()` for the basics
- `db.collection.aggregate({$indexStats: {}})` for the usage
- `db.collection.stats()` for index sizes
It exposes a `fetch()` function which data-service can call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/6)
=> add support for new index-model@0.4.0 and tests.

lib/ssh-tunnel-connector.js, test/ssh-tunnel-connector.test.js
ssh2 is lazily loaded essentially so in order to test failure scenarios
and ensure the tunnel is truly ready, we attempt to write against it.
This way we’ll get a proper SSH connect failure error instead of the
node.js driver connection error.
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/21)
=> INT-1510: Test an SSH tunnel is writable when creating

lib/data-service.js, lib/native-client.js, test/data-service.test.js, test/helper.js, test/native-client.test.js
To allow for DDL manipulation in Compass, I added 6 methods:
- createCollection
- dropCollection
- createIndex
- dropIndex
- createDatabase
- dropDatabase
Creating a DB wasn't as straightforward as the other operations, and I may end up altering the process as I learn more about what is required for DDL in Compass. Also, to force MongoDB to save a new DB, I had to create a collection in it, which I called "default." There may be a better way to do this, but this was the easiest method I could find.
=> INT 1851: DDL manipulation

package.json
this includes the promoteValues option, which can now be passed through as part of the `options`.
=> bump mongodb-collection-sample@1.3.0

.travis.yml
noticing this in different repos that use mongo-runner for tests. it seems there has been a change and we now need to enable `sudo: required` in the travis config to make these tests work. 
Similar problem here: https://github.com/mongodb-js/collection-sample/pull/81/commits/3517fc74ba5f88631f2dd6e04a18159a3552c7b9
=> require sudo in travis config.

test/data-service.test.js, test/native-client.test.js
In server versions > 3.2, the system indexes are included in the listCollections call which causes our tests to fail. Changed the tests so that they check each returned collection for the correct name and options instead of comparing the entire object.
A fix for this was included in the listIndexes refactor but that PR is still on hold.
See https://github.com/mongodb-js/data-service/issues/75
=> Fix tests to deal with listCollections including system indexes in >3.2

lib/native-client.js, test/native-client.test.js
This is so we don't error out on the entire list of collections - we can have empty stats results for readonly views with no error.
=> Skip readonly view errors on collstats.

lib/data-service.js, lib/native-client.js, test/data-service.test.js, test/native-client.test.js
The first step in our charts epic is to add support for aggregation to the data service.
Aggregation calls in the driver support both callbacks and returning a cursor. Since we're going to have a large number of usages for aggregations, the data service and native client functions also support both options.
=> COMPASS-567 - Add aggregation to data-service.

lib/data-service.js, lib/native-client.js, package.json, test/native-client.test.js
adds `.isMongos`, similar to `.isWritable` (in fact just one of the `isWritable` conditions).
Also adding tests by mocking a `mongodb-connection-model`, just as much as the `NativeClient#connect` method is concerned. 
```
this.database.admin().command({ ismaster: 1 }, (error, result) => {
```
`this.database` is the object that needs to be mocked, that's why it looks a bit complex.
=> COMPASS-615 mongos detection

package.json
Avoids potential issue in 2.4.0:
https://github.com/visionmedia/debug/blob/master/CHANGELOG.md#241--2016-12-13
https://github.com/mongodb-js/data-service/issues/77
=> :arrow_up: debug@2.6.0

package.json
It’s only really used by connection-model tests.
=> Drop mongodb-connection-fixture from devDependencies

lib/native-client.js
This is required for the explain plan to use indexes in project, skip and limit queries
=> COMPASS-810: Adding options to native client explain

.travis.yml
So we are testing against the Electron-relevant versions for this particularly important component of Compass.
Also drops the `lts/boron` alias in favour of the better supported alias `6`.
=> Update travis.yml: Add node 6 & 7 & 7.4 and mongodb 3.4.x

lib/actions.js, lib/data-service-store.js
When the app registry calls `onConnected` it is already too late to get any of the initial SDAM events so we provide a hook for topology description changed so they can listen to that directly, instead of subscribing to the data service directly after its already been connected to.
=> Add action for initial topology description changed

package.json
Includes transitive dependency bumps as at least one is required, and just in case anything else is affected.
=> Bump mongodb-ns@2

lib/native-client.js
The native client's `.aggregate()` function did not return a proper cursor when a callback was passed in. This was evident by the error message that max document size 16MB was reached (which should never be the case with a cursor).
The node driver `.aggregate()` function only returns a cursor if no callback function is provided, see [this code here](https://github.com/mongodb/node-mongodb-native/blob/01b189de77569523b1ca362e96e6d88a867a0725/lib/collection.js#L2671-L2687). 
This change just mimics the node driver behaviour.
=> COMPASS-1243 aggregate returns cursor when no callback is provided

lib/data-service.js, lib/web-client.js, package.json
- use updated connection model with `connectionType` (Currently using commit hash, once things are stable use npm minor bump)
- data-service.js uses `connectionType` to switch between web-client or native-client
- web-client.js uses `stitchServiceName`
=> CHARTS-308: Use new stitchServiceName property in data-service

lib/instance-detail-helper.js, package-lock.json, package.json, test/fixtures.js, test/instance-detail-helper-mocked.test.js
I have removed filtering of databases and collections in instance-detail-helper.js so that all collections or databases that are present in the permissions are included in the list.
This means that previously, listCollections would not return special collections like 'db.system.namespaces'/etc, and now it does.
I've tested it with an admin user, a user with DB-level auth, and a user with collection-level auth. 
@durran let me know if this is what you want and I'll update the tests.
=> COMPASS-3035 - Reduce permissions requirements

lib/data-service.js, lib/native-client.js, test/data-service.test.js
=> COMPASS-3523: Add CRUD API's for Views

lib/instance-detail-helper.js, package-lock.json, test/fixtures.js, test/instance-detail-helper-mocked.test.js
This adds a field called `isGenuineMongoDB` to the InstanceDetail that is returned to the InstanceModel on fetch. The value of `isGenuineMongoDB` is `{isGenuine: <bool>, dbType: <string: cosmosdb/documentdb/mongodb>}`.
This value will be then added to the InstanceModel so it will be accessible globally, in this PR: https://github.com/mongodb-js/instance-model/pull/121
=> Add isGenuine to InstanceHelper

README.md, lib/instance-detail-helper.js, package-lock.json, package.json, test/instance-detail-helper-mocked.test.js, test/instance-detail-helper.test.js
3 new properties of an item in `details.collections[]` so we can have richer metadata for views:
```
type: get(resp, 'type', 'collection'), // collection || view
view_on: get(resp, 'options.viewOn', undefined), // NOTE: this is the collection name the view is based only and not a namespace string
pipeline: get(resp, 'options.pipeline', undefined) // the view's pipeline definition 
```
=> COMPASS-2755: Extend instance details to include richer view props

package-lock.json, package.json, test/native-client.test.js
This PR updates the node.js driver from `3.3.2` to the latest release `3.3.4`. It contains many improvements and bug fixes. [The full changelog is below](#node-changelog). 
**Changelog Highlights**
> [NODE-2274](https://jira.mongodb.org/browse/NODE-2274) "Unified topology never regains nodes which temporarily go down" 
Fixes the underlying cause of timeout-related errors such as "Server selection timed out" with more details in COMPASS-3849 COMPASS-3728. The pull request mongodb/node-mongodb-native#2197 contains much more context on the fix, and a [new design document](https://github.com/mongodb/node-mongodb-native/blob/master/docs/reference/content/reference/unified-topology/index.md) includes how and why the node.js driver team chose this architecture and future improvements it will …
=> COMPASS-3943: Update to latest node driver 3.3.4

package-lock.json, package.json
Ude a new version of the connection model without empty compression in uri
=> COMPASS-3971 clean uri from an empty compression

.travis.yml
Thanks to the findings in mongodb-js/collection-sample#96 we can update config yaml to get travis back to integration testing latest stable and unstable releases. 
> Related COMPASS-3820:
We were on `trusty` (Ubuntu 14.04) which mdb server no longer supports resulting in `mongodb-version-manager` failing to download server installer assets. Simply switching to `bionic` (Ubuntu 18.04) and now we can download those assets correctly again.
travis-ci/apt-source-safelist#410 
Provides the second required update for `ppa:ubuntu-toolchain-r/test`
https://github.com/travis-ci/apt-source-safelist/issues/410#issuecomment-533555025
Appears to have gone away. Some other modules like mongodb-js/storage-mixin need to unlock keychain in CI so we can hunt for more details then. …
=> feat(ci): Integration test latest stable and unstable server releases

package-lock.json, package.json, test/data-service.test.js, test/native-client.test.js
Updating dependencies:
```
☉ [update-deps] data-service/ ncu -u async lodash mongodb mongodb-collection-sample mongodb-index-model mongodb-ns chai electron-mocha electron-rebuild mocha mongodb-js-precommit
Upgrading /Users/lucas/data-service/package.json
[====================] 11/11 100%
async                       ^3.1.0  →    ^3.2.0
lodash                     ^4.17.0  →  ^4.17.15
mongodb                     ^3.5.2  →    ^3.5.4
mongodb-collection-sample   ^4.4.4  →    ^4.5.1
mongodb-index-model         ^2.5.0  →    ^2.6.0
mongodb-ns                  ^2.0.0  →    ^2.2.0
chai                        ^3.4.1  →    ^4.2.0
electron-mocha              ^8.1.2  →    ^8.2.1
electron-rebuild            ^1.8.8  →   ^1.10.0
mocha                       ^7.0.0  →    ^7.1.0
mongodb-js-precommit …
```
=> chore: COMPASS-4191: Update deps

package-lock.json, package.json
Bump the `connection-model` version to one that uses driver's srvHost to get rid of extra pasring on our side.
If this PR approved, and I am OOO, pls create Compass' PR for bumping `data-service` and `connection-model` versions in dependencies and ask @mmarcon to reply on https://jira.mongodb.org/browse/COMPASS-4315
More info here: https://github.com/mongodb-js/connection-model/pull/295
=> COMPASS-4315: use driver's srvHost

lib/data-service.js, lib/native-client.js, test/data-service.test.js
COMPASS-4345
This PR adds the method `findOneAndUpdate` to the data service so that compass-crud can use it. Previously we were using `findOneAndUpdate`. We're switching to `findOneAndUpdate` to provide a better experience to the user in the cases where a document was modified in the background between when they were shown the document and they perform updates.
=> COMPASS-4345: Add findOneAndUpdate

lib/instance-detail-helper.js, package-lock.json, package.json, test/instance-detail-helper-mocked.test.js
COMPASS-4116
Now we're using the more up to date https://github.com/mongodb-js/mongodb-build-info for getting data lake (vscode and mongosh use this package). Previously we were seeing if it was datalake based on the `queryEngine` in the `buildInfo`. Now there's a datalake prop. Not sure when changed, haven't looked deeper.
Before:
After:
=> COMPASS-4116: Fix datalake telemetry - update datalake check to use build info package

lib/instance-detail-helper.js
=> COMPASS-4260: Use getGenuineMongoDB and isEnterprise from mongodb-build-info

lib/native-client.js, test/native-client.test.js
`collStats` does not provide the `readonly` information, so don’t
make up a possibly incorrect value and instead omit the key.
=> COMPASS-4353 - Do not report bogus readonly key from collectionStats

package-lock.json, package.json
Uses a new `mongodb-connection-model` that does not try to add the scheme if missing.
=> COMPASS-4380: Bump mongodb-connection-model to 17.0.0

lib/native-client.js
This makes it much easier to trace what database operations actually
performs under the hood :)
=> chore: enable debugging for all NativeClient methods

package-lock.json, package.json
To pull in https://github.com/mongodb-js/connection-model/pull/330
Not quite sure why connection-model here is a dep and not a peer dependency
=> deps: bump connection model for removal of x509 username validation

package-lock.json, package.json
Also bumps connection model to pull in https://github.com/mongodb-js/connection-model/pull/337 COMPASS-4534 fix.
This deps change should ensure we don't accidentally have two mongodb or connection model version in compass.
On peer dependencies: https://nodejs.org/en/blog/npm/peer-dependencies/
=> deps: move mongodb and connection-model to peer deps

lib/instance-detail-helper.js, lib/native-client.js, package-lock.json, package.json, test/instance-detail-helper-mocked.test.js
In 3.6.3 the driver updated how operations are run so that operations which have the aspect `WRITE_OPERATION` default to primary instead of using the connection's readPreference:
https://github.com/mongodb/node-mongodb-native/commit/ddcd03d0f934d11a0707dd7d89bc4cb165775f55
This PR updates our use of the `db.command` function which is one of those operations with the aspect `WRITE_OPERATION` to explicitly pass the readPreference which the user set up in Compass. This makes it so we have the same behavior as before and previous direct connections to secondaries don't suddenly stop working.
I think we could do a lot of cleanup here. I'm also not quite sure why we're using `db.command` for listing databases instead of `db.listDatabases`. This should fix the issue though. We also shouldn't be …
=> fix: Explicitly pass read preference with db.command commands COMPASS-4539

lib/instance-detail-helper.js, lib/native-client.js, package-lock.json, package.json, test/instance-detail-helper-mocked.test.js
Reverts mongodb-js/data-service#282
The changes here are good, but the changes build on the changes in https://github.com/mongodb-js/data-service/pull/280 which need to be reverted since the big package-lock changes. so we can revert this one first.
=> Revert "fix: Explicitly pass read preference with db.command commands COMPASS-4539"

lib/instance-detail-helper.js, lib/native-client.js, package-lock.json, package.json, test/instance-detail-helper-mocked.test.js
This PR is https://github.com/mongodb-js/data-service/pull/282 just without the many package-lock.json changes, since those probably have some unintended consequences in Compass.
Here's the copy pasted description from that one.
In 3.6.3 the driver updated how operations are run so that operations which have the aspect `WRITE_OPERATION` default to primary instead of using the connection's readPreference:
https://github.com/mongodb/node-mongodb-native/commit/ddcd03d0f934d11a0707dd7d89bc4cb165775f55
This PR updates our use of the `db.command` function which is one of those operations with the aspect `WRITE_OPERATION` to explicitly pass the readPreference which the user set up in Compass. This makes it so we have the same behavior as before and previous direct connections to secondaries …
=> read preference fix without tons of package lock changes

lib/data-service.js, test/data-service.test.js
COMPASS-4568
Previously we were sending the data service with the `data-service-initialized` event. This event would pass a connection which is not guaranteed to successfully connect, and keeping it around in other plugins will cause unexpected errors. We are removing data-service-initialized event to avoid using an unreliable connection. When removing it we still need to listen to the server topology description changed event which occurs before connecting. 
This PR updates the data service to store the most recent server [TopologyDescription](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring-monitoring.rst#events) so that we no longer need to listen to a non-connected connection inside of Compass plugins which …
=> feat: add saving last seen topology description COMPASS-4568

.depcheckrc, .eslintrc, lib/data-service.js, lib/instance-detail-helper.js, lib/native-client.js, package-lock.json, package.json, test/data-service.test.js, test/helper.js, test/native-client.test.js
- Drop `mongodb-collection-sample`
- Add a sample method that directly runs an $sample aggregation.
- Add `startSession` and `killSession` methods.
Other changes:
- Replace `mongodb-js-precommit` with separate `eslint`, `depcheck` and `pre-commit` (i keep having issues with `eslint` and VSCode like that, also the depcheck there simply doesn't catch any real problem)
=> feat: aways sample with aggregation and allow to start and kill sessions COMPASS-4154 

lib/native-client.js, package-lock.json, package.json, test/native-client.test.js
Follow-up to https://github.com/mongodb-js/connection-model/pull/352 that makes sure that when `connection-model` returns a tunnel during connect, we close it before resolving a `disconnect` callback
=> fix: Use latest connection-model and keep reference to tunnel to be able to close it when disconnecting native client COMPASS-4474

lib/data-service.js, lib/native-client.js, test/data-service.test.js
We want to expose this information so that we can check if client is connected before using any methods on it in compass plugins
=> feat: Add isConnected method to dataService to allow easy access to connection status of the internal MongoClient COMPASS-4741

lib/native-client.js, test/helper.js, test/native-client.test.js
There seems to be a bug in driver v3.6 that doesn't pass `sort` correctly to the server when passed as an option of `find` method. This PR adds a workaround for this by calling `sort` method on the cursor instead which driver handles differently
=> fix(native-client): Set sort by using Cursor.sort method instead of passing it as a find option COMPASS-4258
