mongodb-js/data-service

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/2)

:arrow_up: mongodb-connection-model@4.0.2

---

lib/native-client.js
package.json
test/native-client.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/3)

:bug: Use mongodb-ns for ns parsing

---

lib/data-service.js
lib/native-client.js
lib/router.js
package.json
test/native-client.test.js
test/router.test.js

@durran please review. 
It appears that the node driver does not yet support explain verbosity. I left a `@todo` comment in the code explaining that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/7)

INT-1136 add `explain` method, route, and tests.

---

lib/native-client.js
package.json
test/native-client.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/12)

INT-1331: Human readable error messages.

---

lib/data-service.js
lib/ssh-tunnel-connector.js
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/16)

INT-1408: Implement SSH tunnel connector

---

lib/data-service.js
lib/native-client.js
test/data-service.test.js
test/native-client.test.js

Adds the ability to insert, update, and delete single documents.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/18)

INT-1160: CRUD Support in data service.

---

README.md

typo on L39 from handleReadable to handleReadble
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/19)

Update README typo of handleReadable

---

package.json

$indexStats will degrade gracefully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/20)

INT-1520: :arrow_up: mongodb-instance-model@0.5.3

---

lib/data-service.js
lib/native-client.js
test/data-service.test.js
test/native-client.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/24)

INT-1495: Support Multi-Document CRUD

---

lib/data-service.js
lib/native-client.js
test/native-client.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/25)

WIP Serverstats

---

lib/data-service.js
lib/native-client.js
test/data-service.test.js
test/native-client.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/data-service/47)

INT-1802: Support for document validation.

---

.travis.yml
package.json

Based on https://github.com/mongodb-js/connection-model/pull/138

Standardise mongodb-runner CI

---

package.json

chore(package): update mongodb to version 2.2.22

---

lib/actions.js
lib/data-service-store.js
lib/data-service.js
lib/native-client.js
test/data-service-store.test.js
test/data-service.test.js
test/helper.js
test/native-client.test.js

This aims to consolidate all instance-model calls in [fetch.js](https://github.com/mongodb-js/instance-model/blob/master/lib/fetch.js) to here.

COMPASS-801 Add instance commands

---

package.json

includes new algorithm to determine better sampling behavior, e.g. find when asking for more than count documents. Also uses atlasSize to determine if Compass is talking to an Atlas Free Tier instance.

COMPASS-742 bump collection-sample@1.5.0

---

package.json

bump collection-sample@1.5.1

---

package.json

chore(package): update mongodb-connection-model to version 6.4.2

---

package.json

chore(package): update mongodb to version 2.2.24

---

package.json

This pull request upgrades `mongodb-collection-sample` to`1.6.0`, [mongodb-js/collection-sample#90](https://github.com/mongodb-js/collection-sample/pull/90).

COMPASS-890: Undo special-casing `allowDiskUse` for Atlas

---

package.json
test/native-client.test.js

This also changes an existing test error message. For details of why, please see https://github.com/mongodb-js/data-service/commit/c77c2b31639c809417707889a7ed2d0a0f5de562

Bump mongodb @ 2.2.25

---

lib/web-client.js

Include the upDateOne command to the webclient for stitch.

Add updateOne to web-client

---

lib/instance-detail-helper.js

https://jira.mongodb.org/browse/COMPASS-2990

Fix Compass bug when connect to Azure Cosmos

---

lib/native-client.js
package-lock.json
test/native-client.test.js

For some reason installing data-service changes package-lock.json that then causes one of the tests to fail. For the sake of getting this done before monday, I reverted package-lock and made the error message checks as flexible as possible.

COMPASS-3666 - Return raw error from driver

---

package-lock.json
package.json
test/instance-detail-helper.test.js

Switching to the connection model 14 that uses the driver's parser

COMPASS-3607 Switching to the connection model 14

---

package-lock.json
package.json

**Description**
Update `mongodb-connection-model` to v14.2.4 in order to fix server `appname` missing in metadata.
**Checklist**
**Types of changes**

COMPASS-3887 Make sure appname is properly set

---

package-lock.json
package.json

Update connection model version with `appname` fix.

COMPASS-3893 Connect screen issues

---

package-lock.json
package.json

COMPASS-3618 add connection color

---

package-lock.json
package.json

Use connection model where color saved as a string.

COMPASS-3618 color as a string

---

package-lock.json
package.json

Use a new version of the connection model, that throws the type error in case of using a string value instead of an object value when creating a connection instance.

COMPASS-3971 connection from must be async

---

package-lock.json
package.json

Use a new version of the connection model that allows to unsel all properties.

COMPASS-3971 allow unset props

---

package-lock.json
package.json

Switch to the latest version of the connection model.

COMPASS-3991 Update to node driver 3.3.5

---

package-lock.json
package.json

Include mongodb-js/url#19 to fix mongodb-js/compass-connect#82

chore: COMPASS-4017: Update mongodb-url to latest w deps fix

---

package.json

Use `mongodb-connection-model@14.4.3` that urlencodes credentials when using X509 auth.

COMPASS-4104: urlencode credentials when using X509 auth

---

package.json

Use mongodb 3.5.2

---

package-lock.json
package.json

chore: remove extraneous triejs dep

---

package-lock.json
package.json

Use a new version of connection model with default kerberosServiceName.

COMPASS-4089: set default kerberosServiceName

---

package-lock.json
package.json

Use a connection model that has safeUrl.

COMPASS-408: a connection model with safeUrl

---

package-lock.json
package.json

https://github.com/mongodb/node-mongodb-native/releases/tag/v3.5.6
More tests for https://github.com/mongodb-js/compass/pull/1937

chore(deps): COMPASS-4229 Update node driver to v3.5.6

---

package-lock.json
package.json

Update `connection-model` dependency that removes kerberos native npm module.

VSCODE-81 remove extraneous kerberos native

---

package-lock.json
package.json

Use connection model v16 that uses node driver v3.5.6.

fix: use connection model v16

---

package-lock.json
package.json

Use a new version of the connection model with ssh tunnel fix.

COMPASS-4268: Use connection model with ssh tunnel fix

---

package-lock.json
package.json

- Use `connection-mode` with `driverUrlWithSsh`
- Get rid of electron dependencies

VSCODE-122: Use connection model with ssh url

---

package-lock.json
package.json

Use connection model with electron 6 to ensure plugins consistency with Compass.

Build: Use connection model with electron 6

---

package-lock.json
package.json

Bamp `connection-model` version that uses a real auth instead of safe password when building `driverUrlWithSsh`.

Fix: Use a real auth instead of safe password

---

lib/instance-detail-helper.js
test/instance-detail-helper-mocked.test.js

Just like `show dbs` in mongo-cli.
when user has no privilege to execute listDatabases, it also can get dbs in UI

Fallback with connectionStatus when listDatabases is not authorized

---

package-lock.json
package.json

COMPASS-4369: fix storage-mixin:find response callback called twice

---

package-lock.json
package.json

bump connection model to fix SCRAM-SHA-256 uri

---

package-lock.json
package.json

COMPASS-4478 - Update mongodb driver to 3.6.3

---

lib/instance-detail-helper.js
test/instance-detail-helper-mocked.test.js

fix: parseBuildInfo failing with datalake COMPASS-4522

---

lib/native-client.js
test/native-client.test.js

Fix tests that were checking `isMongos` and `isWritable` props on the native client and fix the methods that define those properties
Spotted that the tests are not running while working on another change, after fixing the tests figured out that the properties are not assigned correctly. Seems like the topology description `topologyType` is [just `type` now](https://github.com/mongodb/node-mongodb-native/blob/3f2f9872455c89bca568486cc2e6f0763ade37d7/lib/core/sdam/topology_description.js#L38) and [`servers` is a `Map`](https://github.com/mongodb/node-mongodb-native/blob/3f2f9872455c89bca568486cc2e6f0763ade37d7/lib/core/sdam/topology_description.js#L42), not an array as the method expected.

fix: Fix isWritable and isMongos check and fix tests for the properties

---

package-lock.json
package.json

Reverts mongodb-js/data-service#280
Must have deleted the package-lock.json and updating it pulls in way too many nested dependency changes.

Revert "deps: move mongodb and connection-model to peer deps"
